services:
  proxy:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    restart: unless-stopped
  api:
    build:
      context: "./TeamFinderAPI"
      dockerfile: Dockerfile
    expose:
      - 5000
    restart: unless-stopped
    depends_on:
      - db
    
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password!23
    user: root
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - "./postgres/data/:/var/lib/postgresql/data"
     