services:
  backend:
    build: .
    depends_on:
      - db
    ports:
      - "3000:4000"
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=true
      - MSSQL_SA_PASSWORD=SAMSSQL!2
      - MSSSQL_PID=Standard
