services:
  proxy:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    restart: unless-stopped
    networks:
      - nginx-network
  api:
    build:
      context: "./server"
      dockerfile: Dockerfile
    expose:
      - 5000
    restart: unless-stopped
    networks:
      - nginx-network
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=TRUE
      - MSSQL_SA_PASSWORD=password!23
      - MSSQL_PID= Developer
    networks:
      - backend
networks:
  nginx-network:
    driver: bridge
  backend:
    driver: bridge
